### ISSUE TITLE
Spinner is not shown if added to a dialog

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/vaadin-spinkit#3]
I tried to create a modal dialog and add the Spinner to show some loading screen. But the spinner isn't visible. In a normal view it works fine.

```kotlin
class LoadingIndicator : Dialog() {
    init {
        val spinner = Spinner(SpinnerType.CIRCLE_FADE).centered().large()
        add(spinner)
        isCloseOnEsc = false
        isCloseOnOutsideClick = false
        isModal = true
    }
}
```

**Comment by mcollovati** [comment]
As a workaround you can add a CSS rule to spinkit element
```
spinkit {
    display: inline-block;
}
```
or define a class and apply it to the Spinner element

**Comment by mcollovati** [comment]
Added css class `.sk-display-block` and helper methods `(set|with)DisplayBlock` on Spinner class
